export const ACTION_GET_SHARE_LINK = 'ACTION_GET_SHARE_LINK';
export const ACTION_GET_SHARE_LINK_COMPLETELY = 'ACTION_GET_SHARE_LINK_COMPLETELY';

export const ACTION_GET_TOP_LANDING_GROUP = 'ACTION_GET_TOP_LANDING_GROUP';
export const ACTION_GET_TOP_LANDING_GROUP_COMPLETELY = 'ACTION_GET_TOP_LANDING_GROUP_COMPLETELY';

export const ACTION_UPDATE_JOIN_GROUP = 'ACTION_UPDATE_JOIN_GROUP';
export const ACTION_UPDATE_JOIN_GROUP_COMPLETELY = 'ACTION_UPDATE_JOIN_GROUP_COMPLETELY';

export const ACTION_GET_GROUP_DETAIL = 'ACTION_GET_GROUP_DETAIL';
export const ACTION_GET_GROUP_DETAIL_COMPLETELY = 'ACTION_GET_GROUP_DETAIL_COMPLETELY';

export const ACTION_GET_GROUP_DETAIL_BY_ID = 'ACTION_GET_GROUP_DETAIL_BY_ID';
export const ACTION_GET_GROUP_DETAIL_BY_ID_COMPLETELY = 'ACTION_GET_GROUP_DETAIL_BY_ID_COMPLETELY';

export const ACTION_GET_MEMBER_PROFILE = 'ACTION_GET_MEMBER_PROFILE';
export const ACTION_GET_MEMBER_PROFILE_FROM_CHAT_DETAIL = 'ACTION_GET_MEMBER_PROFILE_FROM_CHAT_DETAIL';
export const ACTION_GET_MEMBER_PROFILE_COMPLETELY = 'ACTION_GET_MEMBER_PROFILE_COMPLETELY';

export const ACTION_GET_MY_MEMBER_PROFILE = 'ACTION_GET_MY_MEMBER_PROFILE';
export const ACTION_GET_MY_MEMBER_PROFILE_COMPLETELY = 'ACTION_GET_MY_MEMBER_PROFILE_COMPLETELY';

export const ACTION_GET_LIST_MEMBER_GROUP_DETAIL = 'ACTION_GET_LIST_MEMBER_GROUP_DETAIL';
export const ACTION_GET_LIST_MEMBER_GROUP_DETAIL_COMPLETELY = 'ACTION_GET_LIST_MEMBER_GROUP_DETAIL_COMPLETELY';
export const ACTION_RESET_LIST_MEMBER_GROUP_DETAIL_COMPLETELY = 'ACTION_RESET_LIST_MEMBER_GROUP_DETAIL_COMPLETELY';

export const ACTION_ON_SEND_MESSAGE = 'ACTION_ON_SEND_MESSAGE';
export const ACTION_ON_SEND_MESSAGE_COMPLETELY = 'ACTION_ON_SEND_MESSAGE_COMPLETELY';

export const ACTION_ON_RECEIVE_MESSAGE = 'ACTION_ON_RECEIVE_MESSAGE';
export const ACTION_ON_RECEIVE_MESSAGE_COMPLETELY = 'ACTION_ON_RECEIVE_MESSAGE_COMPLETELY';

export const ACTION_GET_MESSAGES_DETAIL = 'ACTION_GET_MESSAGES_DETAIL';
export const ACTION_GET_MESSAGES_DETAIL_COMPLETELY = 'GET_FIRST_LIST_MESSAGES_DETAIL_COMPLETELY';

export const ACTION_GET_MESSAGES_DETAIL_SCROLL_UP = 'ACTION_GET_MESSAGES_DETAIL_SCROLL_UP';
export const ACTION_GET_MESSAGES_DETAIL_SCROLL_UP_COMPLETELY = 'ACTION_GET_MESSAGES_DETAIL_SCROLL_UP_COMPLETELY';

export const ACTION_GET_MESSAGES_DETAIL_SCROLL_DOWN = 'ACTION_GET_MESSAGES_DETAIL_SCROLL_DOWN';
export const ACTION_GET_MESSAGES_DETAIL_SCROLL_DOWN_COMPLETELY = 'ACTION_GET_MESSAGES_DETAIL_SCROLL_DOWN_COMPLETELY';

export const UPDATE_CONVERSATION_LIST = 'UPDATE_CONVERSATION_LIST';
export const UPDATE_CONVERSATION_LIST_COMPLETELY = 'UPDATE_CONVERSATION_LIST_COMPLETELY';

export const GET_FIRST_LIST_CONVERSATION = 'GET_FIRST_LIST_CONVERSATION';
export const GET_FIRST_LIST_CONVERSATION_COMPLETELY = 'GET_FIRST_LIST_CONVERSATION_COMPLETELY';
export const ACTION_LAZY_LOAD_CONVERSATION_LIST = 'ACTION_LAZY_LOAD_CONVERSATION_LIST';
export const ACTION_LAZY_LOAD_CONVERSATION_LIST_COMPLETELY = 'ACTION_LAZY_LOAD_CONVERSATION_LIST_COMPLETELY';

export const ACTION_UPDATE_LAST_SEEN = 'ACTION_UPDATE_LAST_SEEN';
export const ACTION_UPDATE_LAST_SEEN_COMPLETELY = 'ACTION_UPDATE_LAST_SEEN_COMPLETELY';

export const ACTION_GET_LATEST_GROUP_MESSAGE = 'ACTION_GET_LATEST_GROUP_MESSAGE';
export const ACTION_GET_LATEST_GROUP_MESSAGE_COMPLETELY = 'ACTION_GET_LATEST_GROUP_MESSAGE_COMPLETELY';

export const ACTION_GET_CONVERSATION_INFORMATION = 'ACTION_GET_CONVERSATION_INFORMATION';
export const ACTION_GET_CONVERSATION_INFORMATION_COMPLETELY = 'ACTION_GET_CONVERSATION_INFORMATION_COMPLETELY';

export const ACTION_TOGGLE_FAVOURITE_CONVERSATION = 'ACTION_TOGGLE_FAVOURITE_CONVERSATION';

export const ACTION_NONE_RESPONSE = 'ACTION_NONE_RESPONSE';
export const ACTION_GET_RECENT_MESSAGE_GROUP_DETAIL = 'ACTION_GET_RECENT_MESSAGE_GROUP_DETAIL';
export const ACTION_GET_RECENT_MESSAGE_GROUP_DETAIL_COMPLETELY = 'ACTION_GET_RECENT_MESSAGE_GROUP_DETAIL_COMPLETELY';

export const ACTION_MARK_READ_ALL = 'ACTION_MARK_READ_ALL';

export const ACTION_GET_ALL_YOUR_GROUP = 'ACTION_GET_ALL_YOUR_GROUP';
export const ACTION_GET_ALL_YOUR_GROUP_COMPLETELY = 'ACTION_GET_ALL_YOUR_GROUP_COMPLETELY';

export const ACTION_GET_RECENT_MEMBER = 'ACTION_GET_RECENT_MEMBER';
export const ACTION_GET_RECENT_MEMBER_COMPLETELY = 'ACTION_GET_RECENT_MEMBER_COMPLETELY';

export const ACTION_GET_DISCOVER_GROUP = 'ACTION_GET_DISCOVER_GROUP';
export const ACTION_GET_DISCOVER_GROUP_COMPLETELY = 'ACTION_GET_DISCOVER_GROUP_COMPLETELY';

export const ACTION_GET_DISCOVER_GROUP_IDS = 'ACTION_GET_DISCOVER_GROUP_IDS';
export const ACTION_GET_DISCOVER_GROUP_IDS_COMPLETELY = 'ACTION_GET_DISCOVER_GROUP_IDS_COMPLETELY';

export const ACTION_DELETE_CONVERSATION = 'ACTION_DELETE_CONVERSATION';
export const ACTION_DELETE_CONVERSATION_COMPLETELY = 'ACTION_DELETE_CONVERSATION_COMPLETELY';

export const ACTION_BLOCK_CONVERSATION = 'ACTION_BLOCK_CONVERSATION';
export const ACTION_BLOCK_CONVERSATION_COMPLETELY = 'ACTION_BLOCK_CONVERSATION_COMPLETELY';

export const ACTION_RESTORE_CONVERSATION = 'ACTION_RESTORE_CONVERSATION';
export const ACTION_RESTORE_CONVERSATION_COMPLETELY = 'ACTION_RESTORE_CONVERSATION_COMPLETELY';

export const ACTION_TOGGLE_FAVOURITE_MEMBER = 'ACTION_TOGGLE_FAVOURITE_MEMBER';

export const ACTION_UNBLOCK_USER = 'ACTION_UNBLOCK_USER';

export const SELECTED_CONVERSATION = 'SELECTED_CONVERSATION';
export const SELECTED_CONVERSATION_COMPLETED = 'SELECTED_CONVERSATION_COMPLETED';

export const ACTION_GET_UNREAD_MESSAGE = 'ACTION_GET_UNREAD_MESSAGE';
export const ACTION_GET_UNREAD_MESSAGE_COMPLETED = 'ACTION_GET_UNREAD_MESSAGE_COMPLETED';

export const ACTION_GET_STATUS_NOTIFICATION = 'ACTION_GET_STATUS_NOTIFICATION';
export const ACTION_GET_STATUS_NOTIFICATION_COMPLETELY = 'ACTION_GET_STATUS_NOTIFICATION_COMPLETELY';
export const MARK_READ_NOTIFICATION = 'MARK_READ_NOTIFICATION';
